CREATE DATABASE quiz_db;
USE quiz_db;

CREATE TABLE quizzes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question VARCHAR(255) NOT NULL,
  option1 VARCHAR(255) NOT NULL,
  option2 VARCHAR(255) NOT NULL,
  option3 VARCHAR(255) NOT NULL,
  option4 VARCHAR(255) NOT NULL,
  answer VARCHAR(255) NOT NULL
);